
networks:
  jobbie:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    networks:
      - jobbie